---
# Uninstall MapR mapr-kafka-connect-jdbc#
- name: Stop Data Access Gateway
  shell: "maprcli node services -name data-access-gateway -action stop -nodes {{ ansible_fqdn }}"
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-data-access-gateway
  package: name=mapr-data-access-gateway state=absent
  register: gateway_result
- name: Configure.sh -R
  shell: /opt/mapr/server/configure.sh -R
  when: gateway_result.changed