---
# Uninstall Gateway
- name: Check for mapr-clusters.conf
  stat: path=/opt/mapr/conf/mapr-clusters.conf
  register: clusters_conf
- name: Stop Gateway
  shell: "maprcli node services -name gateway -action stop -nodes {{ ansible_fqdn }}"
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
  when: clusters_conf.stat.exists
- name: Uninstall mapr-gateway
  package: name=mapr-gateway state=absent
