---
# Configure secure client
# key store is required for Spark UI
- name: Copy SSL keys to all nodes
  copy: src="/tmp/{{ item }}" dest="/opt/mapr/conf/{{ item }}"
  with_items:
  - ssl_truststore
  - ssl_keystore

- name: Copy mapruserticket to all nodes (required for FUSE or nfsloopback)
  copy: src="/tmp/mapruserticket" dest="/opt/mapr/conf/mapruserticket" mode="0600" owner="{{ mapr_user }}" group="{{ mapr_group }}"  
# copy to other nodes
# run configure on other nodes

- name: Configure.sh for mapr-client - nativesecurity - secure
  shell: "/opt/mapr/server/configure.sh -N {{ cluster_name }} -Z {{ zookeeper_string }} -C {{ cldb_string }} -u {{ mapr_user }} -g {{mapr_group}} -secure -c"