---
# Uninstall Hive Metastore
- name: Stop Hive Metastore
  shell: "maprcli node services -name hivemeta -action stop -nodes {{ ansible_fqdn }}"
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-hivemetastore
  package: name=mapr-hivemetastore state=absent
