---
# Uninstall MapR elasticsearch
- name: Stop Elasticsearch
  shell: "maprcli node services -name elasticsearch -action stop -nodes {{ ansible_fqdn }}"
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-elasticsearch
  package: name=mapr-elasticsearch state=absent
