---
# Restart  Warden
- name: Ensure warden.conf is owned by mapr user
  file: path=/opt/mapr/conf/warden.conf owner="{{ mapr_user }}" group="{{ mapr_group }}"
- name: Stop Warden
  service: name=mapr-warden state=stopped enabled=yes
- name: Delete /opt/mapr/logs/cldb.log
  file: path=/opt/mapr/logs/cldb.log state=absent
- name: Start Warden
  service: name=mapr-warden state=started enabled=yes
# Check on license is required, because when doing first installation, no license was applied
- name: Wait for CLDB
  wait_for: path=/opt/mapr/logs/cldb.log state=present search_regex="CLDB State change \\:\ RUNNING|CLDBShutdown\\:\ license not found for CLDB HA|Becoming Slave Thread" timeout=1800
- pause: seconds="{{ warden_restart_wait_time }}"
  when: ansible_check_mode is undefined or not ansible_check_mode
- name: Check for CLDB not started, because of license
  shell: "cat /opt/mapr/logs/cldb.log | grep 'license not found for CLDB HA'"
  failed_when: false
  register: cldb_license_status
  check_mode: no
- name: Check if CLDB process is running
  shell: "/opt/mapr/initscripts/mapr-cldb status"
  register: cldb_status
  failed_when: cldb_status.stdout.find('CLDB running') == -1
  when: cldb_license_status.rc == 1 # 1 means error from grep, no license error occured
  check_mode: no
