---
# Uninstall Hive WebHCat
- name: Stop WebHCat
  shell: "maprcli node services -name hcat -action stop -nodes {{ ansible_fqdn }}"
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-hivewebhcat
  package: name=mapr-hivewebhcat state=absent
