- name: Write disk tmp file
  shell: echo {{ disks }} | tr , '\n' > /tmp/disks.txt
  when: disks != "find_unused"
- name: Copy find disks script
  copy: src="write_unused_disks.sh" dest="/tmp/write_unused_disks.sh" mode="0755" owner="{{ mapr_user }}" group="{{ mapr_group }}"
  when: disks == "find_unused"
- name: Write unused disks tmp file
  shell: /tmp/write_unused_disks.sh
  when: disks == "find_unused"
- name: Check if disks have been added
  stat: path=/opt/mapr/conf/disktab
  register: disks_added_status
- name: Disk setup
  command: /opt/mapr/server/disksetup -F -W {{ disk_storage_pool_size }} /tmp/disks.txt
  when: not disks_added_status.stat.exists
- set_fact: mfs_local_changes=1
  when: not disks_added_status.stat.exists