---
# Uninstall MapR grafana
- name: Stop Grafana
  shell: "maprcli node services -name grafana -action stop -nodes  {{ ansible_fqdn }}"
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-grafana
  package: name=mapr-grafana state=absent
