---
# Install HttpFS
- name: Install mapr-httpfs
  package: name=mapr-httpfs state=present
  register: httpfs_result

# Other actions
- name: Set owner mapr-system user
  file: path=/opt/mapr/httpfs owner="{{ mapr_user }}" group="{{ mapr_group }}" state=directory recurse=yes

#- name: Find HttpFS
#  find: paths="/opt/mapr/httpfs/" patterns="httpfs*" file_type=directory
#  register: httpfs_path_result
#  failed_when: httpfs_path_result.matched != 1
- name: Get HttpFS version
  shell: cat /opt/mapr/httpfs/httpfsversion
  register: version_output
  check_mode: no
  changed_when: no
- name: Configure httpfs-site.xml
  template: src=httpfs-site.xml dest="/opt/mapr/httpfs/httpfs-{{ version_output.stdout }}/etc/hadoop/httpfs-site.xml"
- name: Enable SSL for HTTPFS since cluster is secure
  copy: remote_src=true src="/opt/mapr/httpfs/httpfs-{{ version_output.stdout }}/share/hadoop/httpfs/tomcat/conf/server.xml.https" dest="/opt/mapr/httpfs/httpfs-{{ version_output.stdout }}/share/hadoop/httpfs/tomcat/conf/server.xml" mode=0644 owner="{{ mapr_user }}" group="{{ mapr_group }}"
  when: httpfs_security != 'none'
- name: Start all httpfs instances
  lineinfile: dest="/opt/mapr/httpfs/httpfs-{{ version_output.stdout }}/etc/hadoop/warden.httpfs.conf" regexp="^services=" line="services=httpfs:all"
- name: Copy to /opt/mapr/conf/conf.d/warden.httpfs.conf
  copy: remote_src=true src="/opt/mapr/httpfs/httpfs-{{ version_output.stdout }}/etc/hadoop/warden.httpfs.conf" dest=/opt/mapr/conf/conf.d/warden.httpfs.conf mode=0644 owner="{{ mapr_user }}" group="{{ mapr_group }}"

- name: Configure.sh -R
  shell: /opt/mapr/server/configure.sh -R
  when: httpfs_result.changed
- pause: seconds=10
  when: httpfs_result.changed
- name: Restart HttpFS
  shell: "maprcli node services -name httpfs -action restart -nodes {{ ansible_fqdn }}"
  register: task_result
  until: task_result.rc == 0
  retries: 10
  delay: 10
  ignore_errors: yes
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
  when: httpfs_result.changed