---
# Uninstall MapR mapr-kafka-rest
- name: Stop Kafka REST
  shell: "maprcli node services -name kafka-rest -action stop -nodes {{ ansible_fqdn }}"
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-kafka-rest
  package: name=mapr-kafka-rest state=absent
  register: kafka_rest_result
- name: Configure.sh -R
  shell: /opt/mapr/server/configure.sh -R
  when: kafka_rest_result.changed