---
- name: Converge
  hosts: all
  roles:
    - role: ../../roles/common-misc
    - role: ../../roles/common-mapruser
    - role: ../../roles/common-misc
    - role: ../../roles/common-ntp
    - role: ../../roles/common-openjdk18
    - role: ../../roles/common-oraclejdk18
    - role: ../../roles/common-prereq
    - role: ../../roles/common-rpcbind
    - role: ../../roles/common-selinux
    - role: ../../roles/common-sysctl
    - role: ../../roles/ext-ad-createusers
    - role: ../../roles/ext-anaconda-python
    - role: ../../roles/ext-anaconda-python-spark
    - role: ../../roles/ext-kerberos5-setup
    - role: ../../roles/ext-kerberos-keytabs-ad-generate
    - role: ../../roles/ext-kerberos-verify-keytabs
    - role: ../../roles/ext-mysql-install
    - role: ../../roles/ext-mysql-uninstall
    - role: ../../roles/ext-nscd-setup
    - role: ../../roles/ext-rlang
    - role: ../../roles/ext-rstudioserverpro
    - role: ../../roles/ext-sssd-ad-setup
    - role: ../../roles/ext-zeppelin
    - role: ../../roles/mapr-cldb-changes
    - role: ../../roles/mapr-cldb-install
    - role: ../../roles/mapr-cldb-uninstall
    - role: ../../roles/mapr-client-configure-fetch-keys
    - role: ../../roles/mapr-client-configure-nativesecurity-fetch
    - role: ../../roles/mapr-client-configure-nativesecurity-secure
    - role: ../../roles/mapr-client-configure-unsecure
    - role: ../../roles/mapr-client-install
    - role: ../../roles/mapr-collectd-install
    - role: ../../roles/mapr-collectd-uninstall
    - role: ../../roles/mapr-configure-disks
    - role: ../../roles/mapr-configure-kerberos
    - role: ../../roles/mapr-configure-nativesecurity-secure
    - role: ../../roles/mapr-configure-repository
    - role: ../../roles/mapr-configure-roles
    - role: ../../roles/mapr-configure-security-fetch-keys
    - role: ../../roles/mapr-configure-subnets
    - role: ../../roles/mapr-configure-unsecure
    - role: ../../roles/mapr-configure-vars-cldb
    - role: ../../roles/mapr-configure-vars-hs
    - role: ../../roles/mapr-configure-vars-rm
    - role: ../../roles/mapr-configure-vars-zk
    - role: ../../roles/mapr-configure-warden-cldb-restart
    - role: ../../roles/mapr-configure-warden-restart
    - role: ../../roles/mapr-configure-zookeeper-restart
    - role: ../../roles/mapr-core-install
    - role: ../../roles/mapr-core-uninstall
    - role: ../../roles/mapr-configure-cleanup
    - role: ../../roles/mapr-data-access-gateway-install
    - role: ../../roles/mapr-data-access-gateway-uninstall
    - role: ../../roles/mapr-drill-standalone-install
    - role: ../../roles/mapr-drill-standalone-uninstall
    - role: ../../roles/mapr-drill-yarn-install
    - role: ../../roles/mapr-drill-yarn-uninstall
    - role: ../../roles/mapr-elasticsearch-install
    - role: ../../roles/mapr-elasticsearch-install-secure
    - role: ../../roles/mapr-elasticsearch-uninstall
    - role: ../../roles/mapr-filemigrate-install
    - role: ../../roles/mapr-filemigrate-uninstall
    - role: ../../roles/mapr-fileserver-install
    - role: ../../roles/mapr-fileserver-uninstall
    - role: ../../roles/mapr-fluentd-install
    - role: ../../roles/mapr-fluentd-install-secure
    - role: ../../roles/mapr-fluentd-uninstall
    - role: ../../roles/mapr-flume-install
    - role: ../../roles/mapr-flume-uninstall
    - role: ../../roles/mapr-gateway-install
    - role: ../../roles/mapr-gateway-uninstall
    - role: ../../roles/mapr-global-vars
    - role: ../../roles/mapr-grafana-install
    - role: ../../roles/mapr-grafana-uninstall
    - role: ../../roles/mapr-hbase-cli-install
    - role: ../../roles/mapr-hbase-cli-uninstall
    - role: ../../roles/mapr-hbase-thrift-rest-install
    - role: ../../roles/mapr-hbase-thrift-rest-uninstall
    - role: ../../roles/mapr-historyserver-changes
    - role: ../../roles/mapr-historyserver-install
    - role: ../../roles/mapr-historyserver-uninstall
    - role: ../../roles/mapr-hive-cli-install
    - role: ../../roles/mapr-hive-cli-uninstall
    - role: ../../roles/mapr-hive-metastore-install
    - role: ../../roles/mapr-hive-metastore-uninstall
    - role: ../../roles/mapr-hive-mysql
    - role: ../../roles/mapr-hive-server2-install
    - role: ../../roles/mapr-hive-server2-uninstall
    - role: ../../roles/mapr-hive-vars
    - role: ../../roles/mapr-hive-webhcat-install
    - role: ../../roles/mapr-hive-webhcat-uninstall
    - role: ../../roles/mapr-httpfs-install
    - role: ../../roles/mapr-httpfs-uninstall
    - role: ../../roles/mapr-hue-install
    - role: ../../roles/mapr-hue-mysql
    - role: ../../roles/mapr-hue-uninstall
    - role: ../../roles/mapr-hue-vars
    - role: ../../roles/mapr-impala-catalog-install
    - role: ../../roles/mapr-impala-catalog-uninstall
    - role: ../../roles/mapr-impala-core-install
    - role: ../../roles/mapr-impala-core-uninstall
    - role: ../../roles/mapr-impala-server-install
    - role: ../../roles/mapr-impala-server-uninstall
    - role: ../../roles/mapr-impala-statestore-install
    - role: ../../roles/mapr-impala-statestore-uninstall
    - role: ../../roles/mapr-impala-vars
    - role: ../../roles/mapr-kafka-connect-jdbc-install
    - role: ../../roles/mapr-kafka-connect-jdbc-uninstall
    - role: ../../roles/mapr-kafka-install
    - role: ../../roles/mapr-kafka-ksql-install
    - role: ../../roles/mapr-kafka-ksql-uninstall
    - role: ../../roles/mapr-kafka-rest-install
    - role: ../../roles/mapr-kafka-rest-uninstall
    - role: ../../roles/mapr-kafka-uninstall
    - role: ../../roles/mapr-kibana-install
    - role: ../../roles/mapr-kibana-install-secure
    - role: ../../roles/mapr-kibana-uninstall
    - role: ../../roles/mapr-log-monitoring-configure
    - role: ../../roles/mapr-log-monitoring-configure-genkeys
    - role: ../../roles/mapr-log-monitoring-configure-vars
    - role: ../../roles/mapr-mapreduce2-install
    - role: ../../roles/mapr-mapreduce2-uninstall
    - role: ../../roles/mapr-mcs-install
    - role: ../../roles/mapr-mcs-uninstall
    - role: ../../roles/mapr-metric-monitoring-configure
    - role: ../../roles/mapr-nfs-v3-install
    - role: ../../roles/mapr-nfsloopback-install
    - role: ../../roles/mapr-nfs-v3-uninstall
    - role: ../../roles/mapr-nodemanager-install
    - role: ../../roles/mapr-nodemanager-localdir
    - role: ../../roles/mapr-nodemanager-uninstall
    - role: ../../roles/mapr-oozie-install
    - role: ../../roles/mapr-oozie-mysql
    - role: ../../roles/mapr-oozie-uninstall
    - role: ../../roles/mapr-opentsdb-custom-install
    - role: ../../roles/mapr-opentsdb-install
    - role: ../../roles/mapr-opentsdb-uninstall
    - role: ../../roles/mapr-patch-client-install
    - role: ../../roles/mapr-patch-install
    - role: ../../roles/mapr-patch-posix-client-basic-install
    - role: ../../roles/mapr-patch-posix-client-basic-uninstall
    - role: ../../roles/mapr-patch-posix-client-platinum-install
    - role: ../../roles/mapr-patch-posix-client-platinum-uninstall
    - role: ../../roles/mapr-patch-uninstall
    - role: ../../roles/mapr-pig-install
    - role: ../../roles/mapr-pig-uninstall
    - role: ../../roles/mapr-posix-client-basic-install
    - role: ../../roles/mapr-posix-client-basic-uninstall
    - role: ../../roles/mapr-posix-client-platinum-install
    - role: ../../roles/mapr-posix-client-platinum-uninstall
    - role: ../../roles/mapr-precheck
    - role: ../../roles/mapr-resourcemanager-install
    - role: ../../roles/mapr-resourcemanager-uninstall
    - role: ../../roles/mapr-spark-historyserver-install
    - role: ../../roles/mapr-spark-historyserver-uninstall
    - role: ../../roles/mapr-spark-thriftserver-install
    - role: ../../roles/mapr-spark-thriftserver-uninstall
    - role: ../../roles/mapr-spark-yarn-install
    - role: ../../roles/mapr-spark-yarn-shuffle-distribute
    - role: ../../roles/mapr-spark-yarn-shuffle-retrieve
    - role: ../../roles/mapr-spark-yarn-uninstall
    - role: ../../roles/mapr-sqoop1-install
    - role: ../../roles/mapr-sqoop1-uninstall
    - role: ../../roles/mapr-sqoop2-client-install
    - role: ../../roles/mapr-sqoop2-client-uninstall
    - role: ../../roles/mapr-sqoop2-server-install
    - role: ../../roles/mapr-sqoop2-server-uninstall
    - role: ../../roles/mapr-sqoop2-server-vars
    - role: ../../roles/mapr-trial-license
    - role: ../../roles/mapr-unregister-node
    - role: ../../roles/mapr-unregister-node-vars
    - role: ../../roles/mapr-zookeeper-changes
    - role: ../../roles/mapr-zookeeper-install
    - role: ../../roles/mapr-zookeeper-uninstall
    - role: ../../roles/ui-setup-init
    - role: ../../roles/ui-setup-nativesecurity-genkeys
    - role: ../../roles/ui-setup-nativesecurity-secure
