---
# Uninstall Impala StateStore
- name: Stop Impala StateStore
  shell: "maprcli node services -name impalastore -action stop -nodes {{ ansible_fqdn }}"
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-impala-statestore
  package: name=mapr-impala-statestore state=absent
