---
# Cannot use Ansible sysctl feature in docker, harder to test with molecule
# https://docs.ansible.com/ansible/2.5/modules/sysctl_module.html?highlight=sysctl
- name: Set vm.swappiness in /etc/sysctl.conf
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "{{item.regex}}"
    line: "{{item.line}}"
    create: true
  with_items:
    - regex: ^vm\.swappiness
      line: vm.swappiness = 1
    - regex: ^net\.ipv4\.tcp_retries2
      line: net.ipv4.tcp_retries2 = 5
    - regex: ^vm\.overcommit_memory
      line: vm.overcommit_memory = 0
    - regex: ^net\.ipv4\.tcp_fin_timeout
      line: net.ipv4.tcp_fin_timeout = 30
  register: sysctl_update
  notify: "Reload Sysctl"
