---
# Uninstall Impala Catalog
- name: Stop Impala Catalog
  shell: "maprcli node services -name impalacatalog -action stop -nodes {{ ansible_fqdn }}"
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-impala-catalog
  package: name=mapr-impala-catalog state=absent
