---
# Uninstall Hive Server 2
- name: Stop HiveServer2
  shell: "maprcli node services -name hs2 -action stop -nodes {{ ansible_fqdn }}"
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-hiveserver2
  package: name=mapr-hiveserver2 state=absent
