---
- name: Stop HBase REST
  shell: "maprcli node services -name hbaserest -action stop -nodes {{ ansible_fqdn }}"
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Stop HBase Thrift
  shell: "maprcli node services -name hbasethrift -action stop -nodes {{ ansible_fqdn }}"
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
# Uninstall HBase REST
- name: Uninstall mapr-hbase-rest
  package: name=mapr-hbase-rest state=absent
# Uninstall HBase Thrift
- name: Uninstall mapr-hbasethrift
  package: name=mapr-hbasethrift state=absent
