---
# Install MapR Client

- name: Install mapr-client
  package: name=mapr-client state=present

# Required for Spark
- name: YARN proxy Jar
  copy: src=/tmp/{{ item | basename }} dest=/opt/mapr/hadoop/hadoop-{{ hadoop_version }}/share/hadoop/yarn/
  with_items: "{{ hostvars[groups['mapr-cldb'][0]].yarnserver_jars_list }}" # set in mapr-client-configure-nativesecurity-fetch

#- name: YARN proxy Jar
#  copy: src=/tmp/hadoop-yarn-server-web-proxy-{{ hadoop_version }}-{{ mapr_build }}.jar dest=/opt/mapr/hadoop/hadoop-{{ hadoop_version }}/share/hadoop/yarn/
## Required for Hive server
#- name: YARN RM Jar
#  copy: src=/tmp/hadoop-yarn-server-common-{{ hadoop_version }}-{{ mapr_build }}.jar dest=/opt/mapr/hadoop/hadoop-{{ hadoop_version }}/share/hadoop/yarn/
#- name: YARN RM Jar
#  copy: src=/tmp/hadoop-yarn-server-resourcemanager-{{ hadoop_version }}-{{ mapr_build }}.jar dest=/opt/mapr/hadoop/hadoop-{{ hadoop_version }}/share/hadoop/yarn/

