---
# Install Flume
# Redhat / CentOS
- name: Install mapr-flume (Redhat / CentOS)
  yum: name=mapr-flume state=present
  when: ansible_os_family == 'RedHat'
# Debian / Ubuntu
- name: Install mapr-flume (Debian / Ubuntu)
  apt: name=mapr-flume state=present allow_unauthenticated=yes
  when: ansible_os_family == 'Debian'
# Suse
- name: Install mapr-flume (Suse)
  zypper: name=mapr-flume state=present
  when: ansible_os_family == 'Suse'