---
- name: Copy MapR keys to all nodes
  copy: src="/tmp/{{ item.filename }}" dest="/opt/mapr/conf/{{ item.filename }}" mode="{{ item.mode }}" owner="{{ mapr_user }}" group="{{ mapr_group }}"
  with_items:
  - filename: maprserverticket
    mode: "0600"
  - filename: cldb.key
    mode: "0600"
- name: Copy MapR keystores and truststores to all nodes
  copy: src="/tmp/{{ item.filename }}" dest="/opt/mapr/conf/{{ item.filename }}" mode="{{ item.mode }}" owner="{{ mapr_user }}" group="{{ mapr_group }}"
  with_items:
  - filename: ssl_keystore
    mode: "0400"
  - filename: ssl_keystore.pem
    mode: "0400"
  - filename: ssl_keystore.p12
    mode: "0400"
  - filename: ssl_truststore
    mode: "0444"
  - filename: ssl_truststore.pem
    mode: "0444"
  - filename: ssl_truststore.p12
    mode: "0444"
  when: not https_custom_certs_enabled
- name: Copy DARE master key
  copy: src=/tmp/dare.master.key dest=/opt/mapr/conf/dare.master.key owner="{{ mapr_user }}" group="{{ mapr_group }}" mode="0600"
  when: security_encryption_rest
 # copy to other nodes
 # run configure on other nodes
- name: Configure.sh secure
  shell: "/opt/mapr/server/configure.sh -N {{ cluster_name }} -Z {{ zookeeper_string }} -C {{ cldb_string }} -u {{ mapr_user }} -g {{mapr_group}} -secure {{ '-dare' if security_encryption_rest else '' }} -HS {{ historyserver_string }} {{ '--isvm' if virtual_machine else '' }}"



