---
# Configure secure cluster
- name: Enable custom security by creating /opt/mapr/conf/.customSecure
  file: path=/opt/mapr/conf/.customSecure state=touch mode=0644
- name: Check if /opt/mapr/conf/cldb.key exists
  stat: path=/opt/mapr/conf/cldb.key
  register: cldb_key_status
- name: Configure.sh to generate keys only run on first mapr-cldb node
  shell: "/opt/mapr/server/configure.sh -N {{ cluster_name }} -Z {{ zookeeper_string }} -C {{ cldb_string }} -u {{ mapr_user }} -g {{ mapr_group }} -genkeys -secure {{ '-dare' if security_encryption_rest else '' }} -HS {{ historyserver_string }} {{ '--isvm' if virtual_machine else '' }}"
  when: inventory_hostname == groups["mapr-cldb"][0] and not cldb_key_status.stat.exists
- name: Copy keys to local
  fetch: src="/opt/mapr/conf/{{ item }}" dest="/tmp/{{ item }}" flat=yes
  with_items:
  - maprserverticket
  - cldb.key
  - ssl_keystore
  - ssl_keystore.pem
  - ssl_keystore.p12
  - ssl_truststore
  - ssl_truststore.pem
  - ssl_truststore.p12
  when: inventory_hostname == groups["mapr-cldb"][0]
- name: Copy DARE master key to local
  fetch: src=/opt/mapr/conf/dare.master.key dest=/tmp/dare.master.key flat=yes
  when: inventory_hostname == groups["mapr-cldb"][0] and security_encryption_rest
- name: Copy keys to all nodes
  copy: src="/tmp/{{ item.filename }}" dest="/opt/mapr/conf/{{ item.filename }}" mode="{{ item.mode }}" owner="{{ mapr_user }}" group="{{ mapr_group }}"
  with_items:
  - filename: maprserverticket
    mode: "0600"
  - filename: cldb.key
    mode: "0600"
  - filename: ssl_keystore
    mode: "0400"
  - filename: ssl_keystore.pem
    mode: "0400"
  - filename: ssl_keystore.p12
    mode: "0400"
  - filename: ssl_truststore
    mode: "0444"
  - filename: ssl_truststore.pem
    mode: "0444"
  - filename: ssl_truststore.p12
    mode: "0444"
- name: Copy DARE master key
  copy: src=/tmp/dare.master.key dest=/opt/mapr/conf/dare.master.key owner="{{ mapr_user }}" group="{{ mapr_group }}" mode="0600"
  when: security_encryption_rest
 # copy to other nodes
 # run configure on other nodes
- name: Configure.sh secure
  shell: "/opt/mapr/server/configure.sh -N {{ cluster_name }} -Z {{ zookeeper_string }} -C {{ cldb_string }} -u {{ mapr_user }} -g {{mapr_group}} -secure {{ '-dare' if security_encryption_rest else '' }} -HS {{ historyserver_string }} {{ '--isvm' if virtual_machine else '' }}"



