---
# Uninstall MapR Kibana
- name: Stop Kibana
  shell: "maprcli node services -name kibana -action stop -nodes {{ ansible_fqdn }}"
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-kibana
  package: name=mapr-kibana state=absent
