---
# Install MapR OpenTSDB configure

- name: Get OpenTSDB FQDNs
  set_fact: opentsdb_item={{ hostvars[item]['ansible_fqdn'] if 'ansible_fqdn' in hostvars[item] else item }}
  with_items:
    - "{{ groups['mapr-opentsdb'] }}"
  register: opentsdb_hosts
- name: Make OpenTSDB String
  set_fact: opentsdb_string={{ opentsdb_hosts.results | map(attribute='ansible_facts.opentsdb_item') | list | join(',')}}
- name: Configure.sh - secure
  shell: /opt/mapr/server/configure.sh -R -OT {{ opentsdb_string }} -EPgrafana '-password {{ spyglass_grafana_password }}' -EPcollectd {{ "-minimal" if spyglass_metrics_collect == "minimal" else "-all" }}
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
    # Workaround for custom security bug
    GRAFANA_ADMIN_ID: "{{ mapr_user }}"
    GRAFANA_ADMIN_PASSWORD: mapr
    # when: mapr_security != 'none'

# - name: Configure.sh
#   shell: /opt/mapr/server/configure.sh -R -OT {{ opentsdb_string }} -EPgrafana '-password {{ spyglass_grafana_password }}'
#   environment:
#     MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
#   when: mapr_security == 'none'
