---
# Uninstall YARN Node Manager
- name: Check role nodemanager
  stat: path=/opt/mapr/roles/nodemanager
  register: role_nodemanager
- name: Stop YARN Node Manager
  shell: "maprcli node services -name nodemanager -action stop -nodes {{ ansible_fqdn }}"
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
  when: role_nodemanager.stat.exists
- name: Uninstall mapr-nodemanager
  package: name=mapr-nodemanager state=absent
